#!/bin/sh

# create pynsist_pkgs folder used in building windows installer
# This is based on the 2-extract.sh script from the pynsist pygi
# example (https://github.com/takluyver/pynsist)

#
# Instructions for building windows installer (64 bit)
#
# Note this can be run on Linux
#
# 1. Install nsis and pynsist
#  
# 2. get gshogi
#
#    git clone https://github.com/johncheetham/gshogi.git
#    cd gshogi
#
# 3. get latest pygi all in one file
#
#    download from https://sourceforge.net/projects/pygobjectwin32/files/
#    eg. pygi-aio-3.24.1_rev1   
#    rename it to pygi.exe (in the jcchess folder)
#
# 4. Get compiled engine module
#
#    To get this compile gshogi or get it from:
#    https://drive.google.com/drive/folders/0B91ZDRXsSFY9a3Zrckc5WXRjcms
#
#    Filename: enginemodule.zip
#    Extract the zip file.
#
# 5. run this script to extract packages
#
#    ./create_pynsist_pkgs
#    (or /create_pynsist_pkgs32 for 32 bit build)
#
# 6. build the installer exe
#
#    python3 -m nsist installer.cfg
#    (or python3 -m nsist installer32.cfg for 32 bit build)
#
# Once this is working you can just do steps 5 and 6 each time.
#
if [ ! -e pygi.exe ]
then
    echo "pygi.exe not found"
    exit
fi

if [ ! -e engine64.pyd ]
then
    echo "engine module not found"
    exit
fi

rm -fr pynsist_pkgs
mkdir pynsist_pkgs

cp engine64.pyd pynsist_pkgs/engine.pyd

# Unzip the bindings
7za x pygi.exe -opygi

# Copy the PyGI packages into the pynsist_pkgs folder
7za x pygi/binding/py3.4-64/py3.4-64.7z -obindings
cp -r bindings/* pynsist_pkgs
rm -r bindings

# Copy the noarch and specified architecture dependencies into the gnome folder
array=( ATK Base GDK GDKPixbuf GTK HarfBuzz JPEG Pango WebP TIFF )

for i in "${array[@]}"
do
    echo -e "\nProcessing $i dependency"
    7za x pygi/noarch/$i/$i.data.7z -o$i-noarch
    cp -r $i-noarch/gnome/* pynsist_pkgs/gnome
    rm -r $i-noarch

    7za x pygi/rtvc10-64/$i/$i.bin.7z -o$i-arch
    cp -r $i-arch/gnome/* pynsist_pkgs/gnome
    rm -r $i-arch
done

#Remove pygi Folder
rm -r pygi

#Compile glib schemas
glib-compile-schemas pynsist_pkgs/gnome/share/glib-2.0/schemas/
